 local menub33e425094ea94d6728d224490e210c9 = {
     {"Accerciser", "/usr/bin/accerciser", "/usr/share/icons/hicolor/16x16/apps/accerciser.png" },
     {"Orca", "orca --replace", "/usr/share/icons/hicolor/16x16/apps/orca.png" },
 }

 local menu89b5111c7b2df663bb5b99c457370421 = {
     {"7-Zip FM", "7zFM", "/usr/share/icons/hicolor/32x32/apps/p7zip.png" },
     {"Calcolatrice", "gnome-calculator", "/usr/share/icons/gnome/16x16/apps/accessories-calculator.png" },
     {"Dischi", "gnome-disks", "/usr/share/icons/hicolor/16x16/apps/gnome-disks.png" },
     {"Gestore di archivi", "file-roller ", "/usr/share/icons/hicolor/16x16/apps/file-roller.png" },
     {"HP Device Manager", "hp-toolbox", "///usr/share/hplip/data/images/128x128/hp_logo.png" },
     {"Orca", "orca --replace", "/usr/share/icons/hicolor/16x16/apps/orca.png" },
     {"Orologi", "gnome-clocks", "/usr/share/icons/hicolor/16x16/apps/gnome-clocks.png" },
     {"Password e chiavi", "/usr/bin/seahorse", "/usr/share/icons/hicolor/16x16/apps/seahorse.png" },
     {"Ricerca desktop", "tracker-needle", "/usr/share/icons/gnome/16x16/actions/system-search.png" },
     {"Schermata", "gnome-screenshot --interactive", "/usr/share/icons/gnome/16x16/apps/applets-screenshooter.png" },
     {"Tabella caratteri", "gucharmap", "/usr/share/icons/gnome/16x16/apps/accessories-character-map.png" },
     {"Terminale root", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"Vi iMproved", "gvim -f ", "/usr/share/pixmaps/gvim.png" },
     {"Visualizzatore di caratteri", "gnome-font-viewer ", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-font.png" },
     {"gedit", "gedit ", "/usr/share/icons/gnome/16x16/apps/accessories-text-editor.png" },
 }

 local menu2fa9d6ced5c4a03264ae97020096503e = {
     {"Adobe Flash Player", "flashplayer", "/usr/share/icons/hicolor/16x16/apps/flash.png" },
     {"Ario", "ario", "/usr/share/icons/hicolor/16x16/apps/ario.png" },
     {"Brasero", "brasero ", "/usr/share/icons/hicolor/16x16/apps/brasero.png" },
     {"Cheese", "cheese", "/usr/share/icons/hicolor/16x16/apps/cheese.png" },
     {"Gnome Music Player Client", "gmpc", "/usr/share/icons/hicolor/16x16/apps/gmpc.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/hicolor/16x16/apps/multimedia-volume-control.png" },
     {"QT V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Rhythmbox", "rhythmbox ", "/usr/share/icons/hicolor/16x16/apps/rhythmbox.png" },
     {"Video", "totem ", "/usr/share/icons/hicolor/16x16/apps/totem.png" },
     {"gMTP", "gmtp", "/usr/share/pixmaps/gMTPicon.png" },
 }

 local menu5598904a204cc436e5c652f27673b58e = {
     {"Cinque o più", "five-or-more", "/usr/share/icons/hicolor/16x16/apps/five-or-more.png" },
     {"Forza 4", "four-in-a-row", "/usr/share/icons/hicolor/16x16/apps/four-in-a-row.png" },
     {"Iagno", "iagno", "/usr/share/icons/hicolor/16x16/apps/iagno.png" },
     {"Klotski", "gnome-klotski", "/usr/share/icons/hicolor/16x16/apps/gnome-klotski.png" },
     {"Mahjongg", "gnome-mahjongg", "/usr/share/icons/hicolor/16x16/apps/gnome-mahjongg.png" },
     {"Mine", "gnome-mines", "/usr/share/icons/hicolor/16x16/apps/gnome-mines.png" },
     {"Nibbles", "gnome-nibbles", "/usr/share/icons/hicolor/16x16/apps/gnome-nibbles.png" },
     {"PlayOnLinux", "playonlinux", "/usr/share/pixmaps/playonlinux32.png" },
     {"Quadrapassel", "quadrapassel", "/usr/share/icons/hicolor/16x16/apps/quadrapassel.png" },
     {"Robots", "gnome-robots", "/usr/share/icons/hicolor/16x16/apps/gnome-robots.png" },
     {"Scacchi", "gnome-chess", "/usr/share/icons/hicolor/16x16/apps/gnome-chess.png" },
     {"Solitario AisleRiot", "sol", "/usr/share/icons/hicolor/16x16/apps/gnome-aisleriot.png" },
     {"Spegni le luci", "lightsoff"},
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Sudoku", "gnome-sudoku", "/usr/share/icons/hicolor/16x16/apps/gnome-sudoku.png" },
     {"Swell Foop", "swell-foop", "/usr/share/icons/hicolor/16x16/apps/swell-foop.png" },
     {"Tali", "tali", "/usr/share/icons/hicolor/16x16/apps/tali.png" },
     {"Tetravex", "gnome-tetravex", "/usr/share/icons/hicolor/16x16/apps/gnome-tetravex.png" },
 }

 local menu62d9be082af29cffc0e05fa11ab23997 = {
     {"Dia Diagram Editor", "dia ", "/usr/share/icons/hicolor/16x16/apps/dia.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/inkscape.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"UFRaw", "ufraw ", "/usr/share/pixmaps/ufraw.png" },
     {"Visualizzatore di immagini", "eog ", "/usr/share/icons/hicolor/16x16/apps/eog.png" },
     {"Visualizzatore documenti", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Dropbox", "dropboxd", "/usr/share/icons/hicolor/16x16/apps/dropbox.png" },
     {"ELinks", "xterm -e /usr/bin/elinks ", "/usr/share/icons/gnome/16x16/mimetypes/html.png" },
     {"Empathy", "empathy", "/usr/share/icons/hicolor/16x16/apps/empathy.png" },
     {"Esploratore Avahi per server SSH", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Esploratore Avahi per server VNC", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Google Chrome", "/opt/google/chrome/google-chrome ", "/usr/share/icons/hicolor/16x16/apps/google-chrome.png" },
     {"Liferea", "liferea", "/usr/share/icons/hicolor/16x16/apps/liferea.png" },
     {"MLDonkey GUI", "mldonkey_gui", "/usr/share/icons/mldonkey.svg" },
     {"RSSOwl", "rssowl", "///usr/share/rssowl/icon.xpm" },
     {"Skype", "skype ", "/usr/share/icons/hicolor/16x16/apps/skype.png" },
     {"Steam", "/usr/bin/steam ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Visualizzatore desktop remoti", "vinagre ", "/usr/share/icons/gnome/16x16/apps/preferences-desktop-remote-desktop.png" },
     {"Web", "epiphany ", "/usr/share/icons/gnome/16x16/apps/web-browser.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
 }

 local menu5464cd25647103af480e2cd7b6db4a0b = {
     {"Accerciser", "/usr/bin/accerciser", "/usr/share/icons/hicolor/16x16/apps/accerciser.png" },
     {"Anjuta", "anjuta ", "/usr/share/icons/hicolor/16x16/apps/anjuta.png" },
     {"Arduino", "arduino", "/usr/share/icons/hicolor/256x256/apps/arduino.png" },
     {"Devhelp", "devhelp", "/usr/share/icons/hicolor/16x16/apps/devhelp.png" },
     {"Eclipse-Android", "/Development/eclipse-android/eclipse", "///Development/eclipse-android/icon.xpm" },
     {"Eclipse-cpp", "/Development/eclipse-cpp/eclipse", "///Development/eclipse-cpp/icon.xpm" },
     {"Eclipse-cpp (Superuser)", "gksu /Development/eclipse-cpp/eclipse", "///Development/eclipse-cpp/icon.xpm" },
     {"Eclipse-java", "/Development/eclipse-java/eclipse", "///Development/eclipse-java/icon.xpm" },
     {"Geany", "geany ", "/usr/share/icons/hicolor/16x16/apps/geany.png" },
     {"Gendarme", "/usr/bin/gendarme-wizard", "/usr/share/pixmaps/gendarme.svg" },
     {"Glade", "glade ", "/usr/share/icons/hicolor/16x16/apps/glade.png" },
     {"Mono Documentation", "/usr/bin/monodoc", "/usr/share/icons/hicolor/16x16/apps/monodoc.png" },
     {"MonoDevelop", "monodevelop ", "/usr/share/icons/hicolor/16x16/apps/monodevelop.png" },
     {"MySQL Workbench", "/usr/bin/mysql-workbench", "/usr/share/icons/hicolor/16x16/apps/mysql-workbench.png" },
     {"Navigatore del database", "gda-browser-5.0", "/usr/share/pixmaps/gda-browser-5.0.png" },
     {"OpenJDK Monitoring & Management Console", "/usr/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"OpenJDK Policy Tool", "/usr/bin/policytool", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"QGit", "/usr/bin/qgit", "/usr/share/pixmaps/qgit.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"gsharp", "/usr/bin/gsharp"},
 }

 local menud1a552dd2b8819a96dff5a0d73817711 = {
     {"Analizzatore di utilizzo del disco", "baobab", "/usr/share/icons/hicolor/16x16/apps/baobab.png" },
     {"Cairo-Dock (no OpenGL)", "cairo-dock -A", "/usr/share/pixmaps/cairo-dock.svg" },
     {"Esploratore Zeroconf Avahi", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"GLX-Dock (Cairo-Dock con OpenGL)", "cairo-dock", "/usr/share/pixmaps/cairo-dock.svg" },
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Gestione stampa", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Guake Terminal", "guake", "/usr/share/icons/hicolor/16x16/apps/guake.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"Monitor di sistema", "gnome-system-monitor", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"Registro di sistema", "gnome-system-log", "/usr/share/icons/hicolor/16x16/apps/logview.png" },
     {"Sakura", "sakura", "/usr/share/pixmaps/terminal-tango.svg" },
     {"Strumenti di rete", "gnome-nettool", "/usr/share/icons/hicolor/16x16/apps/gnome-nettool.png" },
     {"Terminale", "gnome-terminal", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Terminator", "terminator", "/usr/share/icons/hicolor/16x16/apps/terminator.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Wireshark", "wireshark ", "/usr/share/icons/hicolor/16x16/apps/wireshark.png" },
     {"XSensors", "/usr/bin/xsensors", "///usr/share/pixmaps/xsensors/default.xpm" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"dconf Editor", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/dconf-editor.png" },
     {"gtkpacman", "gksu gtkpacman", "///usr/share/gtkpacman/icons/pacman.png" },
     {"urxvt", "urxvt", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
 }

 local menud5206603c52c16df2727bec2ec463c3d = {
     {"Dizionario", "gnome-dictionary", "/usr/share/icons/gnome/16x16/apps/accessories-dictionary.png" },
     {"Evolution", "evolution ", "/usr/share/icons/hicolor/16x16/apps/evolution.png" },
     {"Gestione progetti", "planner ", "/usr/share/pixmaps/gnome-planner.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Texmaker", "texmaker ", "/usr/share/pixmaps/texmaker.png" },
     {"Visualizzatore documenti", "evince ", "/usr/share/icons/hicolor/16x16/apps/evince.png" },
 }

xdgmenu = {
    {"Accessibilità", menub33e425094ea94d6728d224490e210c9},
    {"Accessori", menu89b5111c7b2df663bb5b99c457370421},
    {"Audio & Video", menu2fa9d6ced5c4a03264ae97020096503e},
    {"Giochi", menu5598904a204cc436e5c652f27673b58e},
    {"Grafica", menu62d9be082af29cffc0e05fa11ab23997},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Programmazione", menu5464cd25647103af480e2cd7b6db4a0b},
    {"Strumenti di sistema", menud1a552dd2b8819a96dff5a0d73817711},
    {"Ufficio", menud5206603c52c16df2727bec2ec463c3d},
}

